# ~/.config/starship.toml

add_newline = true

[username]
show_always = true
style_user = "bold green"
format = "[$user]($style) "

[directory]
truncate_to_repo = false
home_symbol = "~"
style = "bold blue"
format = "[$path]($style) "

[git_branch]
symbol = "î‚  "
format = "on [$symbol$branch]($style) "
style = "bold purple"

[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = "bold yellow"

conflicted = "âš” "
ahead      = "â‡¡$count"
behind     = "â‡£$count"
untracked  = "ï‘´"
stashed    = "ğŸ“¦"
modified   = "[âœ $count](bold blue) "
staged     = "[ï‘— $count](bold green) "
renamed    = "Â»"
deleted    = "âœ–"

[character]
success_symbol = "[â¯](bold green) "
error_symbol = "[â¯](bold red) "
